[package]
name = "hellorust"
version = "0.0.1"
authors = ["kevinwenzel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.6.0"}
specs = "0.15.1"
specs-derive = "0.4.0"